---
version: '3'

services:
  gorgeous-golden:
    image: backend
    restart: always
    env_file:
      - .env
    ports:
      - 8000:80
    volumes:
      - strapipublic:/app/cms/public/uploads
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gorgeous.rule=Host(`dev.gorgeous-golden.de`)"
      - "traefik.http.routers.gorgeous.entrypoints=web, websecure"
      - "traefik.http.routers.gorgeous.tls=true"
      - "traefik.http.routers.gorgeous.tls.certresolver=myresolver"
      - "traefik.http.middlewares.test-compress.compress=true"
      - "traefik.http.middlewares.test-http-cache.plugin.httpCache.maxTtl=300"
    networks:
      - default
      - traefik

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - mysqldbvolume:/var/lib/mysql
    env_file:
      - .env

# Volumes
volumes:
  mysqldbvolume:
    driver: local
  strapipublic:
    driver: local

networks:
  traefik:
    external: true
